# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338317e4696e0200ea2eb967678599202449d6cadba96bdcbc4c1a063617d0fa30c0f56bfb3ac535bcaeb6a83bc9721d3c009fbff2fb4565f395baad8ccf82f3

test:
  secret_key_base: af9b6a9ab34de702f26a8216d881e961ed16ff3894996eebeeab4b493075a3846c387745d57c5bc7d9457578bb4b47bc98a3881c52639b2b41212b77ce8e88a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
